name: Build-and Release

on:
  # Запускать сборку при каждом коммите в main
  push:
    branches:
      - main
      - master
    # Запускать при создании тега (например, v1.0.0)
    tags:
      - "v*.*.*"

  # Опционально: запуск при мердже в PR
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pico-sdk
        run: |
          sudo apt install cmake python3 build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
          git clone -b master https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init
          cd ../
          mv pico-sdk ../

      - name: Build project
        run: |
          export PICO_SDK_PATH=/home/runner/work/zxtester/pico-sdk
          pwd
          ls -la ../
          ls -la ../pico-sdk
          ls -la ./

          mkdir -p build
          cd ./build
          cmake ..
          make
          cp ztester.uf2 ../uf2/
          ls -la ../uf2/

      # Условие: публикация релиза только при теге
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
